import type { HexColorCode } from './index';

export type ApiEnv = {
	API_DEBUG: boolean,
	API_HOST: string,
	//API_PUBLIC_URL: string,
	API_PORT: number,
	API_BODY_LIMIT?: number,
	API_HASH_SALT: string,
	API_JWT_SECRET: string,
	API_JWT_TTL: number,
	API_JWT_ISSUER: string,
	API_PASSWORD_RESET_URL_ALLOW_LIST: string[],
	API_USER_INVITE_URL_ALLOW_LIST: string[],
	API_EMAIL_TRANSPORT: string,
	API_EMAIL_FROM_NAME?: string,
	API_EMAIL_FROM_EMAIL?: string,
	API_EMAIL_SENDMAIL_PATH?: string,
	API_SMTP_HOST?: string,
	API_SMTP_USER?: string,
	API_SMTP_PASSWORD?: string,
	API_SMTP_PORT?: number,
	API_SMTP_SECURE?: boolean,
	API_SMTP_IGNORE_TLS?: boolean,
	API_DB_CLIENT: string,
	API_DB_HOST: string,
	API_DB_NAME: string,
	API_DB_USER: string,
	API_DB_PASSWORD: string,
	API_DB_PORT: number,
	API_DB_POOL_MAX?: number,
	API_DB_SSL: boolean,
	APP_NAME: string,
	API_DEFAULT_AUTH_PROVIDER: string
	APP_PUBLIC_URL: string,
	APP_PRIMARY_COLOR: HexColorCode,
}