export const filterOperator = {
	_eq: '=',
	_neq: '!=',
	_lt: '<',
	_lte: '<=',
	_gt: '>',
	_gte: '>=',
	_in: 'in',
	_nin: 'not in',
	_null: 'is null',
	_nnull: 'is not null',
	_contains: 'like',
	_icontains: 'ilike',
	_ncontains: 'not like',
	_starts_with: 'like',
	_istarts_with: 'ilike',
	_nstarts_with: 'not like',
	_nistarts_with: 'not ilike',
	_ends_with: 'like',
	_iends_with: 'ilike',
	_nends_with: 'not like',
	_niends_with: 'not ilike',
	_between: 'between',
	_nbetween: 'not between',
	_empty: 'is null or = false',
	_nempty: 'is not null and != false',
	_intersects: '&&',
	_nintersects: 'not &&',
};
  