#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_APP_USER WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE $POSTGRES_APP_DATABASE;
    GRANT ALL ON DATABASE $POSTGRES_APP_DATABASE TO $POSTGRES_APP_USER;
    ALTER DATABASE $POSTGRES_APP_DATABASE OWNER TO $POSTGRES_APP_USER;
    GRANT ALL ON SCHEMA public TO $POSTGRES_APP_USER;
    ALTER SCHEMA public OWNER TO $POSTGRES_APP_USER;
EOSQL
