version: "3.8"
services:
  db:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: postgres
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_DATABASE: ${POSTGRES_APP_DATABASE}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ../init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 30s
      interval: 10s
      retries: 3